name: Daily Commit

on:
  schedule:
    - cron: '0 6 * * *' # Every day at 6 AM UTC
  workflow_dispatch:    # Also allows manual run from Actions tab

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config user.name "Deepak Yadav"
          git config user.email "deepakk.yadavv.05@gmail.com"  # <-- Replace this

      - name: Make daily commit
        run: |
          echo "Last update: $(date)" > commit.md
          git add commit.md
          git commit -m "Auto daily commit: $(date)"
          git push
